on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A step to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: windymelt/composite-action-exercise@v1
        with:
          who-to-greet: 'Windymelt'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
